# Site settings
title: Joonas Kuorilehto
email: joneskoo@derbian.fi
description: >
  Nörtti, radioamatööri, tietotekniikan DI,
  päivätöissä tietoturva-alalla.
  Kiinnostunut teknologiasta ja säätämisestä.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://joneskoo.kapsi.fi" # the base hostname & protocol for your site

linkedin_username: joneskoo
github_username:  joneskoo
twitter_username: joneskoo_yx
amateur_callsign: OH8GDV
phone_number: +358 500 779 695
vcard_file: /public/joneskoo.vcf

# Build settings
markdown: rdiscount

defaults:
  -
    scope:
      path: "blog"
    values:
      layout: "post"
