title = "Joonas Kuorilehto"
baseurl = "https://joneskoo.yx.fi"
languageCode = "fi-fi"
disablePathToLower = true
theme = "joneskoo"
pygmentsstyle = "vs"

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Nörtti, radioamatööri, tietotekniikan DI, päivätöissä tietoturva-alalla. Kiinnostunut teknologiasta ja säätämisestä. Mielipiteet omia."

[[menu.main]]
    name = "Kuka minä?"
    weight = -110
    identifier = "main"
    url = "/"
