name = "joneskoo"
license = "MIT"
#licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "My own site"
tags = ["blog", "personal"]
features = ["blog", "themes", "disqus"]
min_version = 0.15

[author]
    name = "joneskoo"
    homepage = "https://joneskoo.kapsi.fi"
